name: bmx280
description: Driver for the Bosch BMP280 and BME280 environmental sensors.
environment:
  sdk: ^2.0.0-alpha.196
dependencies:
  sensors:
    url: github.com/toitware/toit-sensors
    version: ^1.0.0
